### ISSUE TITLE
Change redirect page to front end

### ISSUE THREAD

**Issue by jibranb** [lumpysimon/wp-force-password-change#3]
Hi Simon, I changed the redirect page to point to a front end Edit Account page on a WooCommerce site I'm devleloping. At log in or registration, now I end up with a redirect loop and can't quite figure out why. Have you tried this before? Any ideas?

Thanks,
-Jibran

![screen shot 2014-10-15 at 11 41 19 am](https://cloud.githubusercontent.com/assets/3483543/4651281/df8a2e2e-549a-11e4-96da-5e6ace5e5e41.png)

**Comment by LachlanArthur** [comment]
This can be fixed for almost all front-end profile plugins (WooCommerce, TML, etc) by simply checking if the current page is the same as the redirect.

Add this before `if ( ! is_user_logged_in() )`:

```php
if ( wp_make_link_relative( admin_url( 'profile.php' ) ) == $_SERVER['REQUEST_URI'] )
    return;
```

A nice addition would be a filter to allow custom overrides to be added without modifying the plugin.
